### ISSUE TITLE
非常感谢您出色的工作，请问它是怎么运行的？我运行总是出错如下所示。

### ISSUE THREAD

**Issue by xlnn** [QY1994-0919/CFPNet#35]
````
(underspp31) [class1@node01 CFPNet-main]$ python -m cfp.tools.train -f cfp-s -d 2 -b 16 --fp16
Traceback (most recent call last):
  File "/home/CFPNet-main/cfp/exp/build.py", line 13, in get_exp_by_file
    current_exp = importlib.import_module(os.path.basename(exp_file).split(".")[0])
  File "/home/class1/.conda/envs/underspp31/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cfp-s'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/class1/.conda/envs/underspp31/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/class1/.conda/envs/underspp31/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/class1/work/lc/CFPNet-main/tools/train.py", line 114, in <module>
    exp = get_exp(args.exp_file, args.name)
  File "/home/class1/work/lc/CFPNet-main/cfp/exp/build.py", line 40, in get_exp
    return get_exp_by_file(exp_file)
  File "/home/CFPNet-main/cfp/exp/build.py", line 16, in get_exp_by_file
    raise ImportError("{} doesn't contains class named 'Exp'".format(exp_file))
ImportError: cfp-s doesn't contains class named 'Exp'
```
`

**Comment by Sj-Yuan** [comment]
碰到了同样的问题，请问您解决了吗？而且作者已经删除了他们的cfp权重文件，我不知道该如何复现结果
