### ISSUE TITLE
无法对图像进行检测DETECT

### ISSUE THREAD

**Issue by liangfcsu** [QY1994-0919/CFPNet#39]

**Comment by liangfcsu** [comment]
您好 我想咨询一下 我对图像进行detect 如果用Demo.py  直接运行（我已经填写了相关的图像、权重地址）报错
usage: CFP Demo! [-h] [-expn EXPERIMENT_NAME] [-n NAME] [--path PATH]
                 [--camid CAMID] [--save_result] [-f EXP_FILE] [-c CKPT]
                 [--device DEVICE] [--conf CONF] [--nms NMS] [--tsize TSIZE]
                 [--fp16] [--legacy] [--fuse] [--trt]
                 demo
CFP Demo!: error: the following arguments are required: demo
ArgumentParser(prog='CFP Demo!', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)

如果我在终端输入检测指令也会报这个错
Traceback (most recent call last):
  File "/home/Project/Experiment/differ-algorithm/CFPNet-main/tools/demo.py", line 723, in <module>
    exp = get_exp(args.exp_file, args.name)
  File "/home/Project/Experiment/differ-algorithm/CFPNet-main/tools/demo.py", line 607, in get_exp
    return get_exp_by_file(exp_file)
  File "/home/Project/Experiment/differ-algorithm/CFPNet-main/tools/demo.py", line 583, in get_exp_by_file
    raise ImportError("{} doesn't contains class named 'Exp'".format(exp_file))
ImportError: /home/Project/Experiment/differ-algorithm/CFPNet-main/exps/example/custom/cfp_s.py doesn't contains class named 'Exp'
但我查看cfp_s.py 这个文件 Exp类 是已经存在的 
请问我需要怎么解决这个问题，非常感谢您！
